/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SystemAdminWorkArea;

import Business.Doctor.Doctor;
import Business.EcoSystem;
import Business.LoginInfo.LoginInfo;
import Business.Reception.Reception;
import Business.Role.DoctorRole;
import Business.Role.ReceptionRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jeetkhimani
 */
public class ManageDoctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDoctorJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;

    public ManageDoctorJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populatedoctortable();
        dispimg();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoctorList = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(1080, 730, 75, 29);

        jLabel1.setText("Doctor Name:");
        add(jLabel1);
        jLabel1.setBounds(606, 421, 87, 16);

        jLabel2.setText("UserName:");
        add(jLabel2);
        jLabel2.setBounds(625, 459, 68, 16);

        jLabel3.setText("Password:");
        add(jLabel3);
        jLabel3.setBounds(630, 497, 63, 16);
        add(txtName);
        txtName.setBounds(711, 416, 104, 26);
        add(txtUsername);
        txtUsername.setBounds(711, 454, 104, 26);
        add(txtPassword);
        txtPassword.setBounds(711, 492, 104, 26);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit);
        btnSubmit.setBounds(667, 536, 88, 29);

        tblDoctorList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Username", "Password"
            }
        ));
        jScrollPane1.setViewportView(tblDoctorList);

        add(jScrollPane1);
        jScrollPane1.setBounds(380, 280, 701, 119);
        add(jLabel4);
        jLabel4.setBounds(500, 0, 430, 280);
    }// </editor-fold>//GEN-END:initComponents
    
    private void dispimg(){
        scaleIcon(430,280,"src/images/doctor.jpg", jLabel4);
    }
    
    public void scaleIcon(int Width, int Height, String imgPath, javax.swing.JLabel jLabel){
        File file = new File(imgPath);
        String absolutePath = file.getAbsolutePath();
        ImageIcon img = new ImageIcon(absolutePath);
        System.out.println(absolutePath);
        Image icon = img.getImage();
        icon = icon.getScaledInstance(Width, Height, Image.SCALE_SMOOTH);
        img = new ImageIcon(icon);
        jLabel.setIcon(img);
        jLabel.setText("");
       
    }
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        
        if (txtName.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Name Missing");
            return;
        }
        if (txtUsername.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Username Missing");
            return;
        }
        if (txtPassword.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Password Missing");
            return;
        }
        if (system.getUserAccountDirectory().checkIfUsernameIsUnique(txtUsername.getText()) == true){
        String username = txtUsername.getText();
        String password = String.valueOf(txtPassword.getText());
        String name = txtName.getText();
        UserAccount account = system.getUserAccountDirectory().createUserAccount(username, password, name, new DoctorRole());
        Doctor doctor = system.getDoctorDirectory().setDoctor(new Doctor(username, password, name));
        txtName.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        populatedoctortable();
        JOptionPane.showMessageDialog(null, "Added new user");
        }
        else {
            JOptionPane.showMessageDialog(null, txtUsername.getText() + " exists. Enter a new username");
        }
        
        
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDoctorList;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void populatedoctortable() {
        DefaultTableModel table = (DefaultTableModel) tblDoctorList.getModel();
        table.setRowCount(0);
        for (Doctor doctor : system.getDoctorDirectory().getDoctorDirectory()) {
            Object[] row = new Object[3];
            row[0] = doctor.getName();
            row[1] = doctor.getUsername();
            row[2] = doctor.getPassword();

            table.addRow(row); 
        }
    }
}
