/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author MyPC1
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        //populateTree();
        dispimg();
    }
    
    /*
    public void populateTree(){
        //DefaultTreeModel model=(DefaultTreeModel)jTree.getModel();
        ArrayList<Network> networkList=ecosystem.getNetworkList();
        ArrayList<Enterprise> enterpriseList;
        ArrayList<Organization> organizationList;
        
        Network network;
        Enterprise enterprise;
        Organization organization;
        
        //DefaultMutableTreeNode networks=new DefaultMutableTreeNode("Networks");
        //DefaultMutableTreeNode root=(DefaultMutableTreeNode)model.getRoot();
        //root.removeAllChildren();
        //root.insert(networks, 0);
        
        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;
        
        for(int i=0;i<networkList.size();i++){
            network=networkList.get(i);
            networkNode=new DefaultMutableTreeNode(network.getName());
            networks.insert(networkNode, i);
            
            enterpriseList=network.getEnterpriseDirectory().getEnterpriseList();
            for(int j=0; j<enterpriseList.size();j++){
                enterprise=enterpriseList.get(j);
                enterpriseNode=new DefaultMutableTreeNode(enterprise.getName());
                networkNode.insert(enterpriseNode, j);
                
                organizationList=enterprise.getOrganizationDirectory().getOrganizationList();
                for(int k=0;k<organizationList.size();k++){
                    organization=organizationList.get(i);
                    organizationNode=new DefaultMutableTreeNode(organization.getName());
                    enterpriseNode.insert(organizationNode, k);
                }
            }
        }
        model.reload();
    }
    
    */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnManageNetwork = new javax.swing.JButton();
        btnManageEnterprise = new javax.swing.JButton();
        btnManageAdmin = new javax.swing.JButton();
        btnManageAdmin1 = new javax.swing.JButton();
        btnManageNetwork1 = new javax.swing.JButton();
        btnManageNetwork2 = new javax.swing.JButton();
        btnManageNetwork3 = new javax.swing.JButton();
        btnManageNetwork4 = new javax.swing.JButton();
        btnManageNetwork5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );

        jSplitPane.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        btnManageNetwork.setBackground(new java.awt.Color(255, 255, 255));
        btnManageNetwork.setText("Manage Doctor");
        btnManageNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetworkActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageNetwork);
        btnManageNetwork.setBounds(561, 424, 219, 29);

        btnManageEnterprise.setBackground(new java.awt.Color(255, 255, 255));
        btnManageEnterprise.setText("Manage User");
        btnManageEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnterpriseActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageEnterprise);
        btnManageEnterprise.setBounds(561, 494, 219, 29);

        btnManageAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnManageAdmin.setText("Manage Pharmacy");
        btnManageAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAdminActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageAdmin);
        btnManageAdmin.setBounds(561, 529, 219, 29);

        btnManageAdmin1.setBackground(new java.awt.Color(255, 255, 255));
        btnManageAdmin1.setText("Manage Pharmacy Inventory");
        btnManageAdmin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAdmin1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageAdmin1);
        btnManageAdmin1.setBounds(561, 564, 219, 29);

        btnManageNetwork1.setBackground(new java.awt.Color(255, 255, 255));
        btnManageNetwork1.setText("Manage Laboratory Tests");
        btnManageNetwork1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetwork1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageNetwork1);
        btnManageNetwork1.setBounds(561, 459, 219, 29);

        btnManageNetwork2.setBackground(new java.awt.Color(255, 255, 255));
        btnManageNetwork2.setText("Manage Reception");
        btnManageNetwork2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetwork2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageNetwork2);
        btnManageNetwork2.setBounds(561, 389, 219, 29);

        btnManageNetwork3.setBackground(new java.awt.Color(255, 255, 255));
        btnManageNetwork3.setText("Manage Insurance Office");
        btnManageNetwork3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetwork3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageNetwork3);
        btnManageNetwork3.setBounds(561, 599, 219, 29);

        btnManageNetwork4.setBackground(new java.awt.Color(255, 255, 255));
        btnManageNetwork4.setText("Manage Billing");
        btnManageNetwork4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetwork4ActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageNetwork4);
        btnManageNetwork4.setBounds(561, 634, 219, 29);

        btnManageNetwork5.setBackground(new java.awt.Color(255, 255, 255));
        btnManageNetwork5.setText("Manage Laboratory Reports");
        btnManageNetwork5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetwork5ActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageNetwork5);
        btnManageNetwork5.setBounds(561, 669, 219, 29);
        jPanel2.add(jLabel1);
        jLabel1.setBounds(-3, 0, 1450, 380);

        jSplitPane.setRightComponent(jPanel2);

        add(jSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
        
    private void dispimg(){
        scaleIcon(1290,380,"src/images/sysadmin.png", jLabel1);
    }
    
    public void scaleIcon(int Width, int Height, String imgPath, javax.swing.JLabel jLabel){
        File file = new File(imgPath);
        String absolutePath = file.getAbsolutePath();
        ImageIcon img = new ImageIcon(absolutePath);
        System.out.println(absolutePath);
        Image icon = img.getImage();
        icon = icon.getScaledInstance(Width, Height, Image.SCALE_SMOOTH);
        img = new ImageIcon(icon);
        jLabel.setIcon(img);
        jLabel.setText("");
       
    }
    
        
    private void btnManageNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetworkActionPerformed
        ManageDoctorJPanel managedoctorJPanel=new ManageDoctorJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("manageNetworkJPanel",managedoctorJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageNetworkActionPerformed

    private void btnManageEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnterpriseActionPerformed
        
        ManageUserJPanel ManageUserJPanel = new ManageUserJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("ManageUserJPanel", ManageUserJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageEnterpriseActionPerformed

    private void btnManageAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAdminActionPerformed
        ManagePharmacyJPanel managePharmacyJPanel=new ManagePharmacyJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("managePharmacyJPanel",managePharmacyJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageAdminActionPerformed

    private void btnManageAdmin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAdmin1ActionPerformed
        // TODO add your handling code here:
        
        ManagePharmacyInventoryJPanel managePharmacyInventoryJPanel=new ManagePharmacyInventoryJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("managePharmacyInventoryJPanel",managePharmacyInventoryJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnManageAdmin1ActionPerformed

    private void btnManageNetwork1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetwork1ActionPerformed
        // TODO add your handling code here:
        ManageLaboratoryTestJPanel ManageLaboratoryTestJPanel = new ManageLaboratoryTestJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("ManageLaboratorytestJPanel", ManageLaboratoryTestJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnManageNetwork1ActionPerformed

    private void btnManageNetwork2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetwork2ActionPerformed
        // TODO add your handling code here:
        
        ManageReceptionJPanel ManageReceptionJPanel = new ManageReceptionJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("ManageReceptionJPanel",ManageReceptionJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnManageNetwork2ActionPerformed

    private void btnManageNetwork3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetwork3ActionPerformed
        // TODO add your handling code here:
        
        ManageInsuranceOfficeJPanel ManageInsuranceOfficeJPanel = new ManageInsuranceOfficeJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("ManageInsuranceOfficeJPanel",ManageInsuranceOfficeJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnManageNetwork3ActionPerformed

    private void btnManageNetwork4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetwork4ActionPerformed
        // TODO add your handling code here:
        ManageBillingJPanel ManageBillingJPanel = new ManageBillingJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("ManageBillingJPanel",ManageBillingJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnManageNetwork4ActionPerformed

    private void btnManageNetwork5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetwork5ActionPerformed
        // TODO add your handling code here:
        
        ManageLabReportJPanel ManageLabReportJPanel = new ManageLabReportJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("ManageLabReportJPanel",ManageLabReportJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_btnManageNetwork5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageAdmin;
    private javax.swing.JButton btnManageAdmin1;
    private javax.swing.JButton btnManageEnterprise;
    private javax.swing.JButton btnManageNetwork;
    private javax.swing.JButton btnManageNetwork1;
    private javax.swing.JButton btnManageNetwork2;
    private javax.swing.JButton btnManageNetwork3;
    private javax.swing.JButton btnManageNetwork4;
    private javax.swing.JButton btnManageNetwork5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane;
    // End of variables declaration//GEN-END:variables
}
